// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbg4G4g6kSkLmB6wN1c9MkSnOqNzKnloM',
    appId: '1:434486179755:web:95d06bdc4557797a4e04ee',
    messagingSenderId: '434486179755',
    projectId: 'tic-tac-toe-9b222',
    authDomain: 'tic-tac-toe-9b222.firebaseapp.com',
    storageBucket: 'tic-tac-toe-9b222.firebasestorage.app',
    measurementId: 'G-E9Y8TTJ0PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xNVYJjDqd02ZBDM0omwhfmKjmIYKeFA',
    appId: '1:434486179755:android:f10a4909d78e8a974e04ee',
    messagingSenderId: '434486179755',
    projectId: 'tic-tac-toe-9b222',
    storageBucket: 'tic-tac-toe-9b222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YBvKKBfc6DgmqmoHKF72srbk4LZZbtw',
    appId: '1:434486179755:ios:05026b7eab7c65464e04ee',
    messagingSenderId: '434486179755',
    projectId: 'tic-tac-toe-9b222',
    storageBucket: 'tic-tac-toe-9b222.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );
}
